<a href="https://colab.research.google.com/github/ektasingh008/DAM/blob/main/DAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Welcome to Business Analytics")

Welcome to Business Analytics

In [ ]:
price = 500
quantity = 10
sales = price*quantity

if sales > 4000:
  print ("Good Sales")
else:
   print("Low sales")

Good Sales

In [ ]:
# Number Type
# 1. Integer
age = 25
print ( age)
print (type (age))

# 2. float
price = 99.50
print(price)
print (type(price))

#3. complex
z = 3 + 4j
print(z)
print (type(z))

25
<class 'int'>
99.5
<class 'float'>
(3+4j)
<class 'complex'>

In [ ]:
#Byjus case
import pandas as pd
import numpy as np

df = pd.read_excel("/content/Lecture2_data (2).xlsx")

In [ ]:
#Data Description
print(df.head)
print(df.shape)
df.info()

<bound method NDFrame.head of    Record_ID         Product       City Quarter  Students_Enrolled  \
0       R001     WhiteHat Jr    Kolkata      Q2                243
1       R002     WhiteHat Jr     Mumbai      Q3                356
2       R003  Aakash Classes    Kolkata      Q3                734
3       R004           Toppr  Bengaluru      Q4                561
4       R005            Osmo  Bengaluru      Q2                331
..       ...             ...        ...     ...                ...
95      R096           Toppr      Delhi      Q4                517
96      R097  Aakash Classes     Mumbai      Q4                937
97      R098     WhiteHat Jr     Mumbai      Q2                371
98      R099  Aakash Classes  Bengaluru      Q1                807
99      R100            Osmo     Mumbai      Q4                414

    Avg_Fee_INR  Discount_Pct  Revenue_Lakh  Marketing_Spend_Lakh  \
0         46500          18.0          92.7                 247.0
1         44000          21.5         123.2                 353.1
2         93200          15.9         575.7                 114.6
3         19500          18.5          89.3                 153.7
4         12200          14.2          34.8                  82.6
..          ...           ...           ...                   ...
95        19700          20.8          80.7                 172.0
96        85300          21.6         626.6                 182.3
97        43200          17.3         132.8                 335.6
98        88100           9.6         643.0                 130.7
99        12100          20.7          39.8                 102.1

    Content_Cost_Lakh  Salary_Cost_Lakh  Other_Cost_Lakh  Sales_Team_Size  \
0                49.9             109.2             39.2               20
1                71.3             105.8             40.6               33
2                88.1             203.9             90.4               17
3                67.4              80.7             34.3               17
4                41.1              48.5             16.3               11
..                ...               ...              ...              ...
95               62.5              72.9             29.0               19
96              133.9             210.7            111.4               27
97               67.8             101.7             41.7               31
98              112.0             185.4             97.1               22
99               48.0              48.2             22.1               12

    Refund_Pct  Customer_Rating
0          8.4              3.9
1          7.4              4.0
2          4.7              4.3
3          8.3              3.7
4          3.2              4.2
..         ...              ...
95         9.4              3.8
96         7.9              4.0
97         6.2              3.9
98         3.9              4.3
99         7.2              4.4

[100 rows x 15 columns]>
(100, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Record_ID             100 non-null    object
 1   Product               100 non-null    object
 2   City                  100 non-null    object
 3   Quarter               100 non-null    object
 4   Students_Enrolled     100 non-null    int64
 5   Avg_Fee_INR           100 non-null    int64
 6   Discount_Pct          100 non-null    float64
 7   Revenue_Lakh          100 non-null    float64
 8   Marketing_Spend_Lakh  100 non-null    float64
 9   Content_Cost_Lakh     100 non-null    float64
 10  Salary_Cost_Lakh      100 non-null    float64
 11  Other_Cost_Lakh       100 non-null    float64
 12  Sales_Team_Size       100 non-null    int64
 13  Refund_Pct            100 non-null    float64
 14  Customer_Rating       96 non-null     float64
dtypes: float64(8), int64(3), object(4)
memory usage: 11.8+ KB

In [ ]:
df.dtypes

Record_ID                object
Product                  object
City                     object
Quarter                  object
Students_Enrolled         int64
Avg_Fee_INR               int64
Discount_Pct            float64
Revenue_Lakh            float64
Marketing_Spend_Lakh    float64
Content_Cost_Lakh       float64
Salary_Cost_Lakh        float64
Other_Cost_Lakh         float64
Sales_Team_Size           int64
Refund_Pct              float64
Customer_Rating         float64
dtype: object

In [ ]:
#Top 10 profit/loss product
df["Total_Cost_Lakh"] = (
    df["Marketing_Spend_Lakh"]
    + df["Content_Cost_Lakh"]
    +df["Salary_Cost_Lakh"]
    +df["Other_Cost_Lakh"]
)
df[ "Profit_Lakh"] = df ["Revenue_Lakh"] - df["Total_Cost_Lakh"]
print(df[["Product", "Revenue_Lakh","Total_Cost_Lakh","Profit_Lakh"]].head(10))

          Product  Revenue_Lakh  Total_Cost_Lakh  Profit_Lakh
0     WhiteHat Jr          92.7            445.3       -352.6
1     WhiteHat Jr         123.2            570.8       -447.6
2  Aakash Classes         575.7            497.0         78.7
3           Toppr          89.3            336.1       -246.8
4            Osmo          34.8            188.5       -153.7
5    Learning App         228.7            521.1       -292.4
6           Toppr          87.4            276.9       -189.5
7  Aakash Classes         595.5            554.9         40.6
8           Toppr          94.4            307.7       -213.3
9     WhiteHat Jr         114.8            566.5       -451.7

In [ ]:
#Missing Value
print(df.isna().sum())

Record_ID               0
Product                 0
City                    0
Quarter                 0
Students_Enrolled       0
Avg_Fee_INR             0
Discount_Pct            0
Revenue_Lakh            0
Marketing_Spend_Lakh    0
Content_Cost_Lakh       0
Salary_Cost_Lakh        0
Other_Cost_Lakh         0
Sales_Team_Size         0
Refund_Pct              0
Customer_Rating         4
Total_Cost_Lakh         0
Profit_Lakh             0
dtype: int64

In [ ]:
# Decision making structures
#If Statements
rating = df["Revenue_Lakh"].mean()

if rating >= 4:
  print("revenue is good")

revenue is good

In [ ]:
# Decision making structures
#If else
revenue = df["Revenue_Lakh"].mean()

if revenue >= 300:
  print("Average revenue is high")
else:
    print("Average revenue is low")

Average revenue is low

In [ ]:
# Decision making structures
# Nested IF Statement in python
revenue = df["Revenue_Lakh"].mean()
rating = df["Customer_Rating"].mean()

if revenue >= 300:
  print("Revenue is high")

  if rating >= 4:
     print("Customer satisfaction is also good")
  else:
      print ("Customer satisfaction needs improvement")

else:
    print("Revenue is low")

Revenue is low

In [ ]:
#WHILE Loop in python
#While loop and i,j is variable to track
i = 0

while i < 5:
  revenue = df["Revenue_Lakh"].iloc[i]

  if revenue >= 300:
      print("High Revenue:", revenue)
  else :
      print("Low Revenue:", revenue)

Streaming output truncated to the last 5000 lines.
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7
Low Revenue: 92.7

In [9]:
#Starbucks Case
import pandas as pd
import numpy as np

# Define the correct file path
file_path = "/content/Starbucks_India_Sales_Dataset.xlsx"

# Load the correct Excel sheets
sales_df = pd.read_excel(file_path, sheet_name="Sales_Data")
products_table = pd.read_excel(file_path, sheet_name="Products")
stores_df = pd.read_excel(file_path, sheet_name="Stores")

# Check the data
print("Sales table:", sales_df.shape)
print("Products:", products_table.shape)
print("Stores:", stores_df.shape)

# Display first 5 rows of stores
stores_df.head()

Sales table: (100, 15)
Products: (8, 4)
Stores: (10, 5)

  StoreID       Store_Name       City Region   Store_Type
0     S01  Connaught Place      Delhi  North  High Street
1     S02       Saket Mall      Delhi  North         Mall
2     S03           Bandra     Mumbai   West  High Street
3     S04     Andheri Mall     Mumbai   West         Mall
4     S05      Indiranagar  Bengaluru  South  High Street

In [10]:
# ---- Part A: create them by typing ----

# LIST: the Starbucks menu (8 products)
menu = ["Cappuccino", "Latte", "Americano", "Cold Brew",
        "Frappuccino", "Masala Chai", "Blueberry Muffin", "Veg Sandwich"]

# TUPLE: one store's fixed details (StoreID, name, city)
store = ("S01", "Connaught Place", "Delhi")

# SET: cities where Starbucks sells (the duplicate 'Delhi' is removed automatically)
cities = {"Delhi", "Mumbai", "Bengaluru", "Hyderabad", "Pune", "Delhi"}

# DICTIONARY: product -> base price in Rs
price = {"Cappuccino": 250, "Latte": 270, "Americano": 220, "Cold Brew": 300,
         "Frappuccino": 350, "Masala Chai": 200, "Blueberry Muffin": 180, "Veg Sandwich": 240}

print("List      :", menu)
print("Tuple     :", store)
print("Set       :", cities, " <- 'Delhi' typed twice, stored once")
print("Dictionary:", price)
print()
print(type(menu), type(store), type(cities), type(price))

List      : ['Cappuccino', 'Latte', 'Americano', 'Cold Brew', 'Frappuccino', 'Masala Chai', 'Blueberry Muffin', 'Veg Sandwich']
Tuple     : ('S01', 'Connaught Place', 'Delhi')
Set       : {'Hyderabad', 'Delhi', 'Bengaluru', 'Pune', 'Mumbai'}  <- 'Delhi' typed twice, stored once
Dictionary: {'Cappuccino': 250, 'Latte': 270, 'Americano': 220, 'Cold Brew': 300, 'Frappuccino': 350, 'Masala Chai': 200, 'Blueberry Muffin': 180, 'Veg Sandwich': 240}

<class 'list'> <class 'tuple'> <class 'set'> <class 'dict'>

In [13]:
# ---- Part B: create them from the Excel data ----
# Each Excel column becomes a Python list. Each Excel row becomes a dictionary.

product_list = sales_df["Product"].tolist()        # 100 products (with repeats)
city_list    = sales_df["City"].tolist()           # 100 cities  (with repeats)
qty_list     = sales_df["Quantity"].tolist()       # 100 quantities
revenue_list = sales_df["Revenue"].tolist()        # 100 revenue values

first_order   = sales_df.iloc[0].to_dict()                 # ONE order  -> dictionary
first_5_orders = sales_df.head(5).to_dict("records")       # FIVE orders -> list of dictionaries

print("Items in product_list :", len(product_list))
print("Unique cities (set)   :", set(city_list))
print()
print("First order as a dictionary:")
print(first_order)

Items in product_list : 100
Unique cities (set)   : {'Hyderabad', 'Delhi', 'Bengaluru', 'Pune', 'Mumbai'}

First order as a dictionary:
{'OrderID': 'SBX1001', 'Date': Timestamp('2026-07-01 00:00:00'), 'City': 'Hyderabad', 'StoreID': 'S07', 'Product': 'Cappuccino', 'Category': 'Hot Coffee', 'Size': 'Grande', 'Unit_Price': 280, 'Quantity': 1, 'Discount_Pct': 0.0, 'Revenue': 280.0, 'Payment_Mode': 'UPI', 'Customer_Type': 'New', 'Order_Channel': 'In-store', 'Rating': 4.0}

In [14]:
# --- List ---
print("First item      :", menu[0])
print("Last item       :", menu[-1])
print("First three     :", menu[0:3])      # slicing: start included, end excluded
print("Every 2nd item  :", menu[::2])

# --- Tuple (same as list) ---
print("\nStore ID        :", store[0])
print("Store city      :", store[2])

# --- Dictionary ---
print("\nPrice of Latte  :", price["Latte"])
print("Safe lookup     :", price.get("Pizza", "Not on menu"))   # no error if key is missing

# --- Set ---
print("\nIs Pune a Starbucks city?   ", "Pune" in cities)
print("Is Jaipur a Starbucks city? ", "Jaipur" in cities)

First item      : Cappuccino
Last item       : Veg Sandwich
First three     : ['Cappuccino', 'Latte', 'Americano']
Every 2nd item  : ['Cappuccino', 'Americano', 'Frappuccino', 'Blueberry Muffin']

Store ID        : S01
Store city      : Delhi

Price of Latte  : 270
Safe lookup     : Not on menu

Is Pune a Starbucks city?    True
Is Jaipur a Starbucks city?  False